coverage:
  status:
    project:
      default:
        enabled: yes
        threshold: 0
        base: auto
        informational: true
    patch:
      default:
        enabled: yes
        threshold: 0
        base: auto
        informational: true

